Replace Drafts logic with Nova Drafts field
outl1ne/nova-page-manager pull request #40
Opened 2020-01-10 13:23 UTC by KasparRosin

Added [nova-drafts](https://github.com/optimistdigital/nova-drafts) field to replace integrated drafts logic.
**All functionality will remain.**

`NovaBlog::draftsEnabled()` is replaced with `NovaBlog::hasNovaDrafts`.
Removed `drafts_enabled` from config. Now it checks whether user has the field package installed.
Removed most of draft logic, that was replaced by nova-drafts

2020-01-10 13:27 UTC, Tarpsvo requested changes

2020-01-10 13:27 UTC, Tarpsvo commented on config/nova-page-manager.php
> -    'drafts_enabled' => false,
Draftid ei ole optional enam?

2020-01-10 13:27 UTC, Tarpsvo commented on src/Models/Page.php
> +
Ebavajalik tab

2020-01-10 13:27 UTC, Tarpsvo commented on src/NovaPageManager.php
> +        return class_exists('\OptimistDigital\NovaDrafts');
Kas siin ei peaks olema` \OptimistDigital\NovaDrafts\NovaDrafts`?

2020-01-10 13:33 UTC, KasparRosin commented on config/nova-page-manager.php
> -    'drafts_enabled' => false,
Ma tegin [sarnase funktsiooni nagu NovaLangiga on](https://github.com/optimistdigital/nova-page-manager/blob/28b7067ef8e1c708f73f87091b4a6254c264a8b3/src/NovaPageManager.php#L31)
Kasutaja peab composeriga installima nova-draftid

2020-01-17 10:10 UTC, Tarpsvo approved these changes

2020-01-17 10:10 UTC, Tarpsvo commented on src/NovaPageManager.php
> +        return class_exists('\OptimistDigital\NovaDrafts\DraftButton') || class_exists('\OptimistDigital\NovaDrafts\PublishedField');
`||` asemel peaks olema `&&`, ei?

2020-01-17 10:10 UTC, merged